name = "JuliaDBMeta"
uuid = "2c06ca41-a429-545c-b8f0-5ca7dd64ba19"
version = "0.4.3"

[deps]
Dagger = "d58978e5-989f-55fb-8d15-ea34adc7bf54"
IndexedTables = "6deec6e2-d858-57c5-ab9b-e6ca5bd20e43"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JuliaDB = "a93385a2-3734-596a-9a66-3cfbb77141e6"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Dagger = "0.7, 0.8, 0.9"
IndexedTables = "0.12.1, 0.13, 1.0"
IterTools = "1"
JuliaDB = "0.10, 0.11, 0.12, 0.13"
MacroTools = "0.4, 0.5"
Reexport = "0.2"
julia = "1.0"

[extras]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Distributed"]
